default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: photokeeper
  password: photokeeper

development:
  <<: *default
  database: photokeeper_development

test:
  <<: *default
  database: photokeeper_test

production:
  <<: *default
  database: photokeeper_production
  username: photokeeper
  password: <%= ENV['PHOTOKEEPER_DATABASE_PASSWORD'] %>
